Generation USA portfolio project 
Michael Allen Latimore
michaelatimore@gmail.com
Personal website for Michael Latimore, Junior Web Developer, to showcase my skills and experiences as a web developer.

twitter_michaelatimore1
https://github.com/michaelatimore
https://www.linkedin.com/in/michael-latimore01?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3B5Xjuf9h8Tf2ia%2FDkjnl2AQ%3D%3D

show_excerpts: true # set to false to remove excerpts on the homepage
